# Generated by Django 5.2.7 on 2025-10-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('niveau_etudes', models.CharField(max_length=100)),
                ('etablissement_origine', models.CharField(max_length=150)),
                ('concours_souhaite', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('extrait_naissance', models.FileField(upload_to='documents/')),
                ('certificat', models.FileField(upload_to='documents/')),
                ('lettre_motivation', models.FileField(upload_to='documents/')),
                ('diplome', models.FileField(upload_to='documents/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
