# Generated by Django 5.2.7 on 2025-10-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='date_inscription',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='etablissement_origine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='prenoms',
            field=models.CharField(max_length=100),
        ),
    ]
