# Generated by Django 5.2.7 on 2025-10-14 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_remove_candidat_date_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
