# Generated by Django 5.2.7 on 2025-10-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_candidat_date_inscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='prenoms',
            new_name='prenom',
        ),
    ]
